FROM python:3.12 AS build

WORKDIR /code


COPY ./requirements.txt /code/requirements.txt


RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt


COPY ./app /code/app

FROM python:3.12

WORKDIR /code


COPY --from=build /code /code


CMD ["fastapi", "run", "app/main.py", "--port", "80"]
